### ISSUE TITLE
mask() can only be used with an image that's the same size.

### ISSUE THREAD

**Issue by premsatha** [cadin/random-comic#1]
Hi,

When I ran the build.pde I ran into this error message mask() can only be used with an image that's the same size. I have not changed anything. 

appreciate if you could help.

Thanks

Regards,
Prema

**Comment by cadin** [comment]
Hi, sorry I didn't see this sooner.
I think you might be getting that error because your config is set to 2x pixel density, but maybe you only have a 1x display? 

In a fresh clone, try changing line 14 from
`Config CONFIG_FULL_RES = new Config(2,       600, 0.125,  0.24,  "600ppi",  false);`
to 
`Config CONFIG_FULL_RES = new Config(1,       600, 0.125,  0.24,  "600ppi",  false);`

The first argument for Config is the pixel density.

**Comment by stihilus** [comment]
Thank you for responsive, that fix the problem 👍
