### ISSUE TITLE
Error: mask() can only be used with an image that's the same size.

### ISSUE THREAD

**Issue by virginiebjt** [cadin/random-comic#2]
When I try building your code, I get this error

`p5: booting...
Loading frames... done:48
loadImageData
IllegalArgumentException: mask() can only be used with an image that's the same size`

It involves the "img.mask(_bgImg); on line 208 of Panel.

I managed to make the program work by deleting this line but the result is less nice!

**Comment by cadin** [comment]
I think you are getting that error because your config is set to 2x pixel density, but maybe you only have a 1x display?

In a fresh clone, try changing line 14 of `build.pde` from
`Config CONFIG_FULL_RES = new Config(2, 600, 0.125, 0.24, "600ppi", false);`
to
`Config CONFIG_FULL_RES = new Config(1, 600, 0.125, 0.24, "600ppi", false);`

The first argument for `Config` is the pixel density.

You're not the only one with this problem. I'll see if I can make that work better, or at least add a note in the README.

**Comment by virginiebjt** [comment]
That solved it! Thanks!!

**Comment by cadin** [comment]
👍
